# Generated by Django 5.2 on 2025-04-10 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField()),
                ('audio_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='transcribe.audiofile')),
            ],
        ),
    ]
