# Generated by Django 5.2 on 2025-04-29 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0002_transcriptionsummary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiofile',
            old_name='audio_url',
            new_name='content',
        ),
        migrations.AlterUniqueTogether(
            name='transcriptsegment',
            unique_together={('audio_file', 'order')},
        ),
    ]
